export enum CommandActions {
  CREATE = "CREATE_COMMAND",
  DELETE = "DELETE_COMMAND",
  CANCEL = "CANCEL_COMMAND",
  VALIDATE = "VALIDATE_COMMAND",
  CREATED = "COMMAND_CREATED",
  VALIDATED = "COMMAND_VALIDATED",
  DELETED = "COMMAND_DELETED"
}
