export enum ProductActions {
  INC_COUNT = "PRODUCT_INC_COUNT",
  DEC_COUNT = "PRODUCT_DEC_COUNT",
  INC_COUNT_SUCCEEDED = "PRODUCT_INC_COUNT_SUCCEEDED",
  DEC_COUNT_SUCCEEDED = "PRODUCT_DEC_COUNT_SUCCEEDED",
  ROLLBACK_DEC_COUNT = "PRODUCT_ROLLBACK_DEC_COUNT",
  ROLLBACK_INC_COUNT = "PRODUCT_ROLLBACK_INC_COUNT"
}
